"""empty message

Revision ID: 2778d76df6bf
Revises: 382ebcc6d200
Create Date: 2014-09-05 23:51:53.738456

"""

# revision identifiers, used by Alembic.
revision = '2778d76df6bf'
down_revision = '382ebcc6d200'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['MeasurementCategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Measurements')
    ### end Alembic commands ###
