"""empty message

Revision ID: 2e7581121dfb
Revises: 2b987c658847
Create Date: 2014-07-15 22:06:31.457549

"""

# revision identifiers, used by Alembic.
revision = '2e7581121dfb'
down_revision = '2b987c658847'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DailyEvaluationChallengeEvaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('evaluation', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['DailyEvaluationChallenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DailyEvaluationChallengeEvaluations')
    ### end Alembic commands ###
