"""empty message

Revision ID: 382ebcc6d200
Revises: 22cc65306494
Create Date: 2014-09-05 23:50:21.919450

"""

# revision identifiers, used by Alembic.
revision = '382ebcc6d200'
down_revision = '22cc65306494'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Measurements')
    op.create_table('MeasurementCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    raise "not supported"
